name: Generate Terraform Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  terraform-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Terraform docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
